export const AI_SALES_ANALYSIS_SCHEMA_VERSION = "AI_SALES_ANALYSIS_V1";
export const AI_SALES_ANALYSIS_PROMPT_VERSION = "AI_SALES_ANALYSIS_PROMPT_V2";
export const AI_SALES_ANALYSIS_TIMEOUT_MS = 8_000;
export const AI_SALES_ANALYSIS_MAX_OUTPUT_TOKENS = 300;
